# Question 19 | Create Secret and mount into Pod
#
# Do the following in a new Namespace secret. Create a Pod named secret-pod of image busybox:1.31.1 which should keep running for some time. It should be able to run on master nodes as well, create the proper toleration.

# There is an existing Secret located at /opt/course/19/secret1.yaml, create it in the secret Namespace and mount it readonly into the Pod at /tmp/secret1.

# Create a new Secret in Namespace secret called secret2 which should contain user=user1 and pass=1234. These entries should be available inside the Pod's container as environment variables APP_USER and APP_PASS.
#
# create ns secret first
# k create ns secret

apiVersion: v1
data:
  halt: TW9uIE1heSAzMCAxMjo1MjoxMCBQTSBQRFQgMjAyMgo=
kind: Secret
metadata:
  name: secret1
  namespace: secret

# k -n secret create secret generic secret2 --from-literal=user=user1 --from-literal=pass=1234
# $ k describe secrets -n secret secret2
# Name:         secret2
# Namespace:    secret
# Labels:       <none>
# Annotations:  <none>
# 
# Type:  Opaque
# 
# Data
# ====
# pass:  4 bytes
# user:  5 bytes
# 

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-pod
  name: secret-pod
  namespace: secret
spec:
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  containers:
  - args:
    - sh
    - -c
    - sleep 5d
    image: busybox:1.31.1
    name: secret-pod
    resources: {}
    env:
    - name: APP_USER
      valueFrom:
        secretKeyRef:
          name: secret2
          key: user
    - name: APP_PASS
      valueFrom:
        secretKeyRef:
          name: secret2
          key: pass
    volumeMounts:
    - name: secret1
      mountPath: /tmp/secret1
      readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: secret1
    secret:
      secretName: secret1
status: {}

## Verify
#
# $ k -n secret exec secret-pod -- env | grep APP
# APP_USER=user1
# APP_PASS=1234
#
# k -n secret exec secret-pod -- find /tmp/secret1
# /tmp/secret1
# /tmp/secret1/..data
# /tmp/secret1/halt
# /tmp/secret1/..2022_05_30_19_55_44.169428471
# /tmp/secret1/..2022_05_30_19_55_44.169428471/halt
# 
# $ k -n secret exec secret-pod -- cat /tmp/secret1/halt
# Mon May 30 12:52:10 PM PDT 2022



