# Create a DaemonSet named ds-important with image httpd:2.4-alpine and labels id=ds-important and uuid=18426a0b-5f59-4e10-923f-c0e078e82462. 
# The Pods it creates should request 10 millicore cpu and 10 mebibyte memory. 
# The Pods of that DaemonSet should run on all nodes, master and worker.
#
# 11.yaml
apiVersion: apps/v1
kind: DaemonSet                                     # change from Deployment to Daemonset
metadata:
  labels:                                           # add
    id: ds-important                                # add
    uuid: 18426a0b-5f59-4e10-923f-c0e078e82462      # add
  name: ds-important
  namespace: project-tiger                          # important
spec:
  selector:
    matchLabels:
      id: ds-important                              # add
      uuid: 18426a0b-5f59-4e10-923f-c0e078e82462    # add
  template:
    metadata:
      labels:
        id: ds-important                            # add
        uuid: 18426a0b-5f59-4e10-923f-c0e078e82462  # add
    spec:
      containers:
      - image: httpd:2.4-alpine
        name: ds-important
        resources:
          requests:                                 # add
            cpu: 10m                                # add
            memory: 10Mi                            # add
      tolerations:                                  # add
      - effect: NoSchedule                          # add
        key: node-role.kubernetes.io/master         # add

# $ k get po -n project-tiger -o wide
# NAME                 READY   STATUS    RESTARTS   AGE   IP           NODE                           NOMINATED NODE   READINESS GATES
# ds-important-p2kkc   1/1     Running   0          17s   10.244.1.3   kind-multi-nod-worker          <none>           <none>
# ds-important-qqtqs   1/1     Running   0          17s   10.244.2.3   kind-multi-nod-worker2         <none>           <none>
# ds-important-rxtqt   1/1     Running   0          17s   10.244.0.5   kind-multi-nod-control-plane   <none>           <none>
# 
