# Create a CustomResourceDefinition manifest file for an Operator with the following specifications :
# 
#     Name : operators.stable.example.com
#     Group : stable.example.com
#     Schema: <email: string><name: string><age: integer>
#     Scope: Namespaced
#     Names: <plural: operators><singular: operator><shortNames: op>
#     Kind: Operator
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: operators.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                email:
                  type: string
                name:
                  type: string
                age:
                  type: integer
  scope: Namespaced
  names:
    plural: operators
    singular: operator
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Operator
    shortNames:
    - op
#
# $ k apply -f crd.yaml
# customresourcedefinition.apiextensions.k8s.io/operators.stable.example.com created
# $ k get crd
# NAME                           CREATED AT
# operators.stable.example.com   2022-07-03T20:15:36Z
#
## NOTE: need apply separately
## Create custom object from the CRD
# 
#     Name : operator-sample
#     Kind: Operator
#     Spec:
#         email: operator-sample@stable.example.com
#         name: operator sample
#         age: 30
---
apiVersion: stable.example.com/v1
kind: Operator
metadata:
  name: operator-sample
spec:
  email: operator-sample@stable.example.com
  name: "operator sample"
  age: 30

# $ k get op
# NAME              AGE
# operator-sample   1s

