# create a secret using original string instead of base64

apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  token: "mytoken"


# Verify
    # $ k get secrets mysecret -o yaml
    # apiVersion: v1
    # data:
    #   token: bXl0b2tlbg==
    #
    # $ echo bXl0b2tlbg== | base64 -d
    # mytoken
