apiVersion: v1
kind: Service
metadata:
  name: node-js
  labels:
    app: node-js
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:     # selector tells which pods can answer the service
    name: node-js
